Lesson18
miheykrug/test-guru pull request #17
Opened 2018-04-04 06:32 UTC by miheykrug

2018-04-04 16:30 UTC, iBublik requested changes

2018-04-04 16:30 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +    var timerEnd = timer.dataset.timerEnd;
Кажется, было бы проще возвращать оставшееся время (в секундах), а не момент окончания попытки

2018-04-04 16:30 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +    if (hours < 10) hours = '0' + hours;
Это можно вынести во вспомогательную функцию

2018-04-04 16:30 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    @test_passage.completed if (params[:end_test_passage] == 'true')
Доверять параметру, пришедшему с клиента, нельзя - опытный пользователь может просто удалить из формы это поле, и тогда сможет игнорировать ограничение по времени

2018-04-04 16:30 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    @timer_end = (@test_passage.created_at.to_f * 1000).to_i + @test_passage.test.timer * 60 * 1000
Лучше в модель вынести метод `time_left`, который будет возвращать оставшееяся время (в секундах)

2018-04-04 16:30 UTC, iBublik commented on app/views/shared/_timer.html.slim
> += content_tag :div, id: 'timer', data: { timer_end: @timer_end } do
Ты предполагаешь переиспользование этого партиала еще где-то?
Если да, то тут нельзя использовать `@`-переменные - потом концы не найдешь, откуда данные пришли
Если нет, то зачем выносить в `shared`?

2018-04-06 06:46 UTC, miheykrug commented on app/assets/javascripts/utilities/timer.js
> +    var timerEnd = timer.dataset.timerEnd;
Тут не совсем понял. Если мы будем высчитывать остаток времени в контроллере, то как передавать это значение в data-атрибут каждую секунду, чтобы отсчет времени работал корректно?

2018-04-06 06:47 UTC, miheykrug commented on app/controllers/test_passages_controller.rb
> +    @test_passage.completed if (params[:end_test_passage] == 'true')
Тут пока даже мыслей нет

2018-04-06 07:29 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +    var timerEnd = timer.dataset.timerEnd;
Так я не предлагаю отказываться от таймера на фронте. Просто ты сюда передаешь значение в мс, из-за чего везде делить приходится на 1000 - это же неудобно

2018-04-06 07:29 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    @test_passage.completed if (params[:end_test_passage] == 'true')
У тебя модель знает момент оконочания попытки. Просто отталкивайся от него - если приходит апдейт после этого момента, то попытка тут же завершается, и проходить тест дальше становится невозможно

2018-04-06 16:41 UTC, psylone approved these changes

2018-04-06 16:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
>        redirect_to result_test_passage_path(@test_passage)
Неплохо бы ещё пользователю готоврить о том что время вышло.

2018-04-12 10:04 UTC, merged