Lesson 18: fix badges
miheykrug/test-guru pull request #18
Opened 2018-04-09 08:13 UTC by miheykrug

2018-04-09 18:14 UTC, iBublik requested changes

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +  RULES = { all_backend?: 'Успешное прохождение всех тестов из категории Backend',
А зачем тебе набор правил хранить в константе? Лучше перебирай весь список бейджей

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +  IMAGES = %w[backend.png easy.png first.png]
Это явно не относится к этому сервису

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +    badges = []
У тебя есть список бейджей - `Badge.all`. Для выбора бейджей, который ты можешь выдать, лучше использовать метод `select` с блоком - он как раз предназначен для фильтрации коллекций

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +      if send(rule, current_user) && !current_user.badges.exists?(badge.id)
Логичнее сразу проверять отсутствие бейджа у пользователя, а уже потом делать более сложные проверки

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +  def self.check_badges(current_user)
Проще test_passage сюда передать - из него проще всю нужную инфу извлечь

2018-04-09 18:14 UTC, iBublik commented on app/services/giving_badges_service.rb
> +  class << self
Можно было все методы обернуть в `class << self`, а не только приватные. Но вообще тут удобнее инстанцировать класс, чтоб не пробрасывать в аргументах текущего пользователя

2018-04-09 20:00 UTC, miheykrug commented on app/services/giving_badges_service.rb
> +  RULES = { all_backend?: 'Успешное прохождение всех тестов из категории Backend',
Пока решил оставить, т.к. в форме создания тестов из этой константы берутся значения для хелпера `f.select`, чтобы администратору не пришлось руками вбивать имя метода при создании бэйджа.

2018-04-09 20:00 UTC, miheykrug commented on app/views/admin/badges/_form.html.slim
> +    = f.select :file_name, Badge::IMAGES, prompt: true
Пытался вместо константы создавать массив файлов при помощи `Dir['app/assets/images/badges/*']`. Но выдает массив с полным путем к файлу (начиная от /app). 
Предполагаю, что можно перебрать каждый элемент массива и отрезать лишнее при помощи slice (например `'app/assets/images/badges/backend.png'[25..-1]` дает нужный результат). Но может быть есть более элегантный способ?

2018-04-10 05:08 UTC, iBublik commented on app/models/badge.rb
> +  IMAGES = %w[backend.png easy.png first.png].freeze
Ну вот это более приемлемо, т.к. скорее к модели относится, нежели к сервису

2018-04-10 05:08 UTC, iBublik commented on app/views/admin/badges/_form.html.slim
> +    = f.select :file_name, Badge::IMAGES, prompt: true
`Dir['app/assets/images/badges/*'].map { |path| File.basename(path) }`

2018-04-10 05:08 UTC, iBublik commented on app/services/giving_badges_service.rb
> +  RULES = { all_backend?: 'Успешное прохождение всех тестов из категории Backend',
Перенеси тогда в модель, тут все аналогично картинкам

2018-04-10 05:08 UTC, iBublik commented on app/services/giving_badges_service.rb
> +    Badge.all.select { |badge| !@user.badges.exists?(badge.id) && send(badge.rule.to_sym) }
К символу не обязательно приводить, `send` и со строками работает

2018-04-10 22:41 UTC, psylone approved these changes

2018-04-10 22:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +      badges = GivingBadgesService.new(@test_passage).check_badges
`check_badges` больше похоже на метод который возвращает `true|false`. Лучше назвать `select_badges`.

2018-04-10 22:41 UTC, psylone commented on app/services/giving_badges_service.rb
> +  RULES = { all_backend?: 'Успешное прохождение всех тестов из категории Backend',
Либо в отдельную модель. А тексты необходимо вынести в файлы локализации.

2018-04-12 09:51 UTC, merged